### ISSUE TITLE
'Connection: close' header.

### ISSUE THREAD

**Issue by turboezh** [webdeskltd/dadata#18]
Hi.

PR #3 added a `Connection: close` header. This prevents connection reusing and slows down response time in about 3 times. In browser all connections are `keep-alive`, so why not in API?
Maybe it's better to remove it and let `http.Transport` to control this behavior?

**Comment by monoflash** [comment]
Arguments are good.
Closing the Body should be left but the headline is superfluous.

**Comment by monoflash** [comment]
Will you make a PR?

**Comment by monoflash** [comment]
#19
