### ISSUE TITLE
json: cannot unmarshal string into Go struct field Address.qc_complete of type int

### ISSUE THREAD

**Issue by fred-kruger** [webdeskltd/dadata#20]
The example doesn't work.

sendRequestToURL: json.Decode return err = json: cannot unmarshal string into Go struct field Address.qc_complete of type int

I can run example after change type from int to interface {}
	QualityCodeComplete interface{} `json:"qc_complete"`    // Код полноты
	QualityCodeHouse    interface{} `json:"qc_house"`       // Код проверки дома
	QualityCode         interface{} `json:"qc"`             // Код качества

**Comment by monoflash** [comment]
Do not use empty golang interfaces. Golang is not php!
In any case, I didn't understand what exactly you could not do.
Requires sample code to repeat your error.

**Comment by fred-kruger** [comment]
> Do not use empty golang interfaces. Golang is not php!
You can see that in your code.
	// QualityCodeGeo для clean вызовов он int для suggest в адресе банков он string поэтому в поле поставил interface{} чтобы работало и там и там)\
	QualityCodeGeo      interface{} `json:"qc_geo"`         // Код точности координат

> In any case, I didn't understand what exactly you could not do.
> Requires sample code to repeat your error.
Can you try run example code from "Usage"?
banks, err := daData.SuggestBanks(dadata.SuggestRequestParams{Query: "Кредитный", Count: 3})

**Comment by monoflash** [comment]
If no one make a pull request before me, then I will post the fixes with version 3.
Thanks for helping us find bugs and improve code.

**Comment by monoflash** [comment]
I changed int to interface {}, in the future custom data type will be made and json unmarshaller for it.
